"""
src/tools/github_tool.py — GitHub PR creation via the REST API.

PR creation strategy (in order):
  1. curl subprocess  — confirmed working with classic PAT + repo scope
  2. gh CLI           — fallback if gh is installed and authenticated
  3. local print      — last resort when no credentials available

The requests/urllib libraries are used only for idempotency checks
(GET existing PRs) and PR body updates (PATCH), which don't trigger
the stricter PAT validation path that blocks POST /pulls.

USAGE
─────
Requires GITHUB_TOKEN in environment with 'repo' scope (classic PAT).
Requires PR_REPO in environment: e.g. "rutwickjain87/sast-lab"

PR FORMAT
─────────
Title: fix(sast): <rule_id> in <filename>
Body includes idempotency tag: <!-- sast-autofix:v1 -->
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import requests

log = logging.getLogger(__name__)

IDEMPOTENCY_TAG = "<!-- sast-autofix:v1 -->"
API_BASE = "https://api.github.com"


@dataclass
class PrResult:
    opened: bool
    url: str
    message: str


# ── HTTP helpers (GET / PATCH only — not used for PR creation) ────────────────

def _session(token: str) -> requests.Session:
    s = requests.Session()
    s.headers.update({"Authorization": f"token {token}"})
    return s


def _get(url: str, token: str) -> tuple[int, object]:
    try:
        r = _session(token).get(url, timeout=15)
        return r.status_code, r.json()
    except Exception as exc:
        log.warning("_get failed: %s", exc)
        return 0, {}


def _patch(url: str, token: str, payload: dict) -> tuple[int, object]:
    try:
        r = _session(token).patch(url, json=payload, timeout=15)
        return r.status_code, r.json()
    except Exception as exc:
        log.warning("_patch failed: %s", exc)
        return 0, {}


# ── PR creation via curl (confirmed working with classic PAT) ─────────────────

def _curl_create_pr(
    pr_repo: str, token: str, title: str, head: str, base: str, body: str,
) -> tuple[int, dict]:
    """
    Create a GitHub PR using curl subprocess.

    curl with a bare 'Authorization: token' header is confirmed working
    where requests/urllib both return 403 on some GitHub accounts.
    """
    payload = json.dumps({"title": title, "head": head, "base": base, "body": body})
    cmd = [
        "curl", "--silent", "--show-error",
        "--write-out", "\n%{http_code}",
        "-X", "POST",
        "-H", f"Authorization: token {token}",
        "-H", "Content-Type: application/json",
        "--data", payload,
        f"{API_BASE}/repos/{pr_repo}/pulls",
    ]
    log.info("curl: POST /repos/%s/pulls", pr_repo)
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)

    stdout = result.stdout.strip()
    # Last line is the HTTP status code written by --write-out
    lines = stdout.rsplit("\n", 1)
    body_text = lines[0] if len(lines) == 2 else stdout
    status_str = lines[-1] if len(lines) == 2 else "0"

    try:
        status = int(status_str)
    except ValueError:
        status = 0

    try:
        data = json.loads(body_text)
    except Exception:
        data = {"raw": body_text}

    if result.returncode != 0:
        log.error("curl stderr: %s", result.stderr.strip())

    log.info("curl response: HTTP %d", status)
    return status, data


# ── PR body builder ───────────────────────────────────────────────────────────

def _build_pr_body(finding: dict, fix_summary: str, diff: str) -> str:
    filename = Path(finding["path"]).name
    snippet = finding["code_snippet"].strip()
    if snippet == "requires login":
        snippet = "(semgrep cloud rule — see finding message above)"
    return f"""## SAST Auto-Fix

**Rule:** `{finding['rule_id']}`
**File:** `{filename}` line {finding['line']}
**Severity:** {finding['severity']}

### Finding
{finding['message']}

### Vulnerable code
```python
{snippet}
```

### Fix summary
{fix_summary}

### Diff
```diff
{diff[:3000]}{'...(truncated)' if len(diff) > 3000 else ''}
```

---
> Generated by [SAST Auto-Fixer](../agents/sast-auto-fix/) — AIOps Platform
{IDEMPOTENCY_TAG}"""


# ── gh CLI fallback ───────────────────────────────────────────────────────────

def _try_gh_cli(
    repo_dir: str, branch: str, title: str, body: str,
    base_branch: str, pr_repo: str,
) -> PrResult:
    if not shutil.which("gh"):
        return PrResult(opened=False, url="", message="gh CLI not found")
    log.info("Trying gh CLI fallback...")
    result = subprocess.run(
        ["gh", "pr", "create", "--repo", pr_repo, "--head", branch,
         "--base", base_branch, "--title", title, "--body", body],
        cwd=repo_dir, capture_output=True, text=True,
    )
    if result.returncode == 0:
        url = result.stdout.strip()
        log.info("gh CLI opened PR: %s", url)
        return PrResult(opened=True, url=url, message="PR opened via gh CLI")
    log.error("gh CLI failed: %s", result.stderr.strip())
    return PrResult(opened=False, url="", message=f"gh CLI: {result.stderr.strip()[:200]}")


# ── Main entry point ──────────────────────────────────────────────────────────

def open_pr(
    repo_dir: str,
    branch: str,
    finding: dict,
    fix_summary: str,
    diff: str,
    base_branch: str = "main",
) -> PrResult:
    """
    Push the fix branch and open a GitHub PR.

    Creation order: curl → gh CLI → local print.
    """
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    pr_repo = os.environ.get("PR_REPO", "").strip()

    filename = Path(finding["path"]).name
    title = f"fix(sast): {finding['rule_id']} in {filename}"
    body = _build_pr_body(finding, fix_summary, diff)

    if not token or not pr_repo:
        log.warning("GITHUB_TOKEN or PR_REPO not set — printing diff only.")
        _print_local(title, branch, base_branch, body)
        return PrResult(opened=False, url="", message="No credentials — diff printed locally")

    # ── Push branch ────────────────────────────────────────────────────────────
    from src.tools.git_tool import git_push
    if not git_push(repo_dir, branch):
        return PrResult(opened=False, url="", message=f"git push failed for {branch}")

    owner = pr_repo.split("/")[0]

    # ── Idempotency: check if PR already open for this branch ─────────────────
    status, prs = _get(
        f"{API_BASE}/repos/{pr_repo}/pulls?state=open&head={owner}:{branch}&base={base_branch}",
        token,
    )
    if isinstance(prs, list) and prs:
        pr = prs[0]
        url = pr["html_url"]
        log.info("PR already exists for branch %s: %s — updating body", branch, url)
        _patch(f"{API_BASE}/repos/{pr_repo}/pulls/{pr['number']}", token, {"body": body})
        return PrResult(opened=True, url=url, message="Updated existing PR")

    # ── Create PR via curl (confirmed working with classic PAT) ───────────────
    status, data = _curl_create_pr(pr_repo, token, title, branch, base_branch, body)

    if status in (200, 201):
        url = data.get("html_url", "")
        log.info("PR opened via curl: %s", url)
        return PrResult(opened=True, url=url, message="PR opened")

    # 422 = PR already exists (race condition — fetch existing URL)
    if status == 422:
        status2, prs2 = _get(
            f"{API_BASE}/repos/{pr_repo}/pulls?state=open&head={owner}:{branch}",
            token,
        )
        if isinstance(prs2, list) and prs2:
            url = prs2[0]["html_url"]
            log.info("PR already exists (422 path): %s", url)
            return PrResult(opened=True, url=url, message="PR already exists")

    msg = data.get("message", str(data)) if isinstance(data, dict) else str(data)
    log.warning("curl returned HTTP %d: %s — trying gh CLI", status, msg[:200])

    # ── Fallback: gh CLI ───────────────────────────────────────────────────────
    gh_result = _try_gh_cli(repo_dir, branch, title, body, base_branch, pr_repo)
    if gh_result.opened:
        return gh_result

    # ── All methods failed ─────────────────────────────────────────────────────
    log.error("All PR creation methods failed. curl: HTTP %d — %s", status, msg[:200])
    return PrResult(opened=False, url="", message=f"curl HTTP {status}: {msg[:200]}")


def _print_local(title: str, branch: str, base_branch: str, body: str) -> None:
    print(f"\n{'─' * 60}")
    print(f"  PR TITLE: {title}")
    print(f"  BRANCH  : {branch}")
    print(f"  BASE    : {base_branch}")
    print(f"{'─' * 60}")
    print(body)
    print(f"{'─' * 60}\n")
