"""
src/routers/runs.py — IaC generation run endpoints.

POST /runs      — Submit a run. Returns run_id immediately.
                  Streams progress events via SSE.
GET  /runs/{id} — Poll a run by ID.

TODO — auth:
    Add `user: AuthUser = Depends(require_auth)` to each endpoint once
    Supabase JWT verification is wired (see src/core/auth.py).

TODO — billing:
    Call `billing.record_usage(user_id, tokens_used)` after each run
    to meter Stripe credits (see src/core/billing.py).

TODO — persistence:
    Replace the in-memory _runs dict with a PostgreSQL table so runs
    survive restarts and can be queried across sessions.
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from datetime import datetime, timezone
from typing import AsyncIterator

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

log = logging.getLogger("saas.api.runs")

router = APIRouter(tags=["runs"])

# ── In-memory run store (dev only — replace with DB in production) ────────────
_runs: dict[str, dict] = {}


# ── Request / response models ─────────────────────────────────────────────────

class RunRequest(BaseModel):
    prompt: str = Field(
        ...,
        description="Natural-language description of the infrastructure to generate.",
        examples=["Create an AWS VPC with two public subnets and an EKS cluster"],
        min_length=10,
        max_length=2000,
    )
    provider: str = Field(
        default="aws",
        description="Cloud provider: aws | gcp | azure",
    )
    # TODO — add user_id once auth is wired
    # user_id: str = Field(...)


class RunResponse(BaseModel):
    run_id: str
    status: str          # queued | running | completed | failed
    created_at: str
    prompt: str
    provider: str
    result: dict | None = None   # populated on completion
    error: str | None = None


# ── SSE helpers ───────────────────────────────────────────────────────────────

def _sse(event: str, data: str) -> str:
    """Format a single Server-Sent Events frame."""
    return f"event: {event}\ndata: {data}\n\n"


async def _stream_run(run_id: str, prompt: str, provider: str) -> AsyncIterator[str]:
    """
    Drive the IaC Generator agent and stream progress events to the client.

    Each event is a JSON string. Event types:
        status   — {"status": "running" | "completed" | "failed"}
        node     — {"node": "<langgraph_node_name>", "message": "..."}
        file     — {"filename": "main.tf", "content": "..."}
        error    — {"error": "..."}
        done     — {"run_id": "...", "file_count": N}

    TODO — replace the stub with the real IaC Generator:
        from agents.iac_generator.generate import run_iac_generator
        async for event in run_iac_generator(prompt, provider):
            yield _sse(event["type"], json.dumps(event))
    """
    import json

    _runs[run_id]["status"] = "running"
    # First event always carries the run_id — clients that can't read
    # response headers (e.g. curl without -D) can grab it from here.
    yield _sse("init", json.dumps({"run_id": run_id}))
    yield _sse("status", json.dumps({"status": "running"}))
    await asyncio.sleep(0.1)

    # ── STUB — simulate the 5-node LangGraph pipeline ─────────────────────────
    nodes = ["clarify", "plan", "generate", "validate", "output"]
    for node in nodes:
        msg = {
            "clarify":  f"Clarifying requirements for {provider} infrastructure...",
            "plan":     "Planning resource dependency order...",
            "generate": "Generating Terraform HCL files...",
            "validate": "Running terraform validate...",
            "output":   "Writing final files to disk...",
        }[node]

        _runs[run_id]["current_node"] = node
        yield _sse("node", json.dumps({"node": node, "message": msg}))
        await asyncio.sleep(0.3)  # stub delay — remove when real agent wired

    # ── STUB — simulate generated files ──────────────────────────────────────
    stub_files = {
        "providers.tf": f'terraform {{\n  required_providers {{\n    {provider} = {{\n      source  = "hashicorp/{provider}"\n      version = "~> 5.0"\n    }}\n  }}\n}}\n',
        "main.tf":      f'# Generated by AIOps Platform\n# Prompt: {prompt[:80]}...\n\n# TODO — replace stub with real IaC Generator output\n',
        "variables.tf": 'variable "region" {\n  description = "Cloud region"\n  type        = string\n  default     = "us-east-1"\n}\n',
        "outputs.tf":   '# Outputs will be populated by the IaC Generator\n',
    }

    for filename, content in stub_files.items():
        yield _sse("file", json.dumps({"filename": filename, "content": content}))
        await asyncio.sleep(0.1)

    # ── Mark complete ─────────────────────────────────────────────────────────
    _runs[run_id]["status"] = "completed"
    _runs[run_id]["result"] = {
        "files": list(stub_files.keys()),
        "file_count": len(stub_files),
        "terraform_valid": True,
    }
    _runs[run_id]["completed_at"] = datetime.now(timezone.utc).isoformat()

    yield _sse("status", json.dumps({"status": "completed"}))
    yield _sse("done", json.dumps({
        "run_id": run_id,
        "file_count": len(stub_files),
    }))


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("", status_code=202)
async def create_run(body: RunRequest) -> StreamingResponse:
    """
    Submit an IaC generation run.

    Returns a Server-Sent Events stream. Each event is JSON.
    The client should read until it receives `event: done`.

    TODO — add auth: `user: AuthUser = Depends(require_auth)`
    TODO — add billing: record intent before starting
    """
    run_id = str(uuid.uuid4())
    _runs[run_id] = {
        "run_id": run_id,
        "status": "queued",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "prompt": body.prompt,
        "provider": body.provider,
        "result": None,
        "error": None,
    }

    log.info("run %s queued — provider=%s prompt_len=%d", run_id, body.provider, len(body.prompt))

    return StreamingResponse(
        _stream_run(run_id, body.prompt, body.provider),
        media_type="text/event-stream",
        headers={
            "X-Run-Id": run_id,
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
        },
    )


@router.get("/{run_id}", response_model=RunResponse)
async def get_run(run_id: str) -> RunResponse:
    """
    Poll a run by ID.

    TODO — add auth: `user: AuthUser = Depends(require_auth)`
    TODO — add ownership check: verify run belongs to requesting user
    """
    run = _runs.get(run_id)
    if not run:
        raise HTTPException(status_code=404, detail=f"Run {run_id!r} not found")
    return RunResponse(**run)
